### ISSUE TITLE
Cannot run git-rockstar!

### ISSUE THREAD

**Issue by chankeypathak** [xxfelixxx/git-rockstar#1]
So I cloned git-rockstar repo twice.
1. ~/Desktop/git-rockstar
2. ~/Desktop/pproj/git-rockstar

Then I ran below command

```
chankey@pathak:~/Desktop/git-rockstar$ ~/Desktop/pproj/git-rockstar/git-rockstar git-rockstar 
Cannot run git-rockstar!
```

Note the error 'Cannot run git-rockstar'.

Could you let me know what am I doing wrong?

**Comment by xxfelixxx** [comment]
I guess I need to make it smarter about paths...
It is trying to run the configure script which is in the top level of the
repo.

Try run it from within the repo itself as ./git-rockstar

Felix

**Comment by xxfelixxx** [comment]
Actually, the path is ok, it looks like configure does not run successfully.
Try running ./configure and install anything you may be missing.  

You need to have the following installed:  perl, R, Rscript, xargs, git, wget

**Comment by xxfelixxx** [comment]
Pushed a change to show the configure output:

https://github.com/xxfelixxx/git-rockstar/commit/deafa6bb67414465584cc1107186f297b46d4d3d

Let me know if that works.

Thanks,

Felix

**Comment by chankeypathak** [comment]
Correct. R was missing.
